version: '1.0'

services:
    django:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        ports:
            - 8000:8000
        depends_on:
            - postgres
    postgres:
        image: postgres:16.0
        environment:
            POSTGRES_USER: 'postgres'
            POSTGRES_PASSWORD: 'password'
            POSTGRES_DB: 'ecommerce_db'
        expose:
            - 5432